const productSchema = {
  name: "product",
  title: "Product",
  type: "document",
  fields: [
    { name: "title", title: "Title", type: "string", validation: (rule: { required: () => unknown }) => rule.required() },
    { name: "slug", title: "Slug", type: "slug", options: { source: "title", maxLength: 96 }, validation: (rule: { required: () => unknown }) => rule.required() },
    { name: "price", title: "Price (GHS)", type: "number", validation: (rule: { required: () => { positive: () => unknown } }) => rule.required().positive() },
    { name: "description", title: "Description", type: "text", rows: 4 },
    { name: "image", title: "External image URL", type: "url" },
    { name: "images", title: "Product images", type: "array", of: [{ type: "image", options: { hotspot: true } }] },
    { name: "category", title: "Category", type: "string" },
    { name: "badge", title: "Drop label", type: "string" },
    { name: "colors", title: "Available colors", type: "array", of: [{ type: "string" }], options: { layout: "tags" } },
    { name: "sizes", title: "Available sizes", type: "array", of: [{ type: "string" }], options: { layout: "tags" } },
    {
      name: "inventory",
      title: "Stock by size",
      type: "array",
      of: [{
        type: "object",
        fields: [
          { name: "size", title: "Size", type: "string", validation: (rule: { required: () => unknown }) => rule.required() },
          { name: "quantity", title: "Units on hand", type: "number", validation: (rule: { required: () => { integer: () => { min: (value: number) => unknown } } }) => rule.required().integer().min(0) },
        ],
        preview: { select: { title: "size", subtitle: "quantity" } },
      }],
    },
    { name: "featured", title: "Feature on storefront", type: "boolean", initialValue: false },
    { name: "active", title: "Store status", type: "boolean", initialValue: true },
    { name: "dtfPlacement", title: "Print / decoration placement", type: "string" },
    { name: "fabric", title: "Fabric / weight", type: "string" },
    { name: "dropName", title: "Drop / collection name", type: "string", validation: (rule: { max: (value: number) => unknown }) => rule.max(80) },
    { name: "storyTitle", title: "Story headline", type: "string", validation: (rule: { max: (value: number) => unknown }) => rule.max(100) },
    { name: "story", title: "Behind the piece", type: "text", rows: 5, validation: (rule: { max: (value: number) => unknown }) => rule.max(1600) },
    { name: "stylingNotes", title: "Styling notes", type: "text", rows: 3, validation: (rule: { max: (value: number) => unknown }) => rule.max(500) },
    { name: "printMethod", title: "Print method", type: "string", options: { list: ["DTF", "DTG", "Embroidered"] } },
    {
      name: "artwork",
      title: "Graphic artwork",
      type: "object",
      fields: [
        { name: "top", title: "Top line", type: "string" },
        { name: "center", title: "Main graphic text", type: "string" },
        { name: "bottom", title: "Bottom line", type: "string" },
        { name: "palette", title: "Graphic palette", type: "string" },
      ],
    },
    {
      name: "reviews",
      title: "Customer reviews",
      type: "array",
      of: [{
        type: "object",
        fields: [
          { name: "customerName", title: "Customer name", type: "string", validation: (rule: { required: () => unknown }) => rule.required() },
          { name: "rating", title: "Star rating", type: "number", validation: (rule: { required: () => { integer: () => { min: (value: number) => { max: (value: number) => unknown } } } }) => rule.required().integer().min(1).max(5) },
          { name: "comment", title: "Review", type: "text", rows: 4, validation: (rule: { required: () => unknown }) => rule.required() },
          { name: "createdAt", title: "Submitted at", type: "datetime" },
          { name: "verifiedPurchase", title: "Verified purchase", type: "boolean", initialValue: false },
          { name: "sizePurchased", title: "Size purchased", type: "string" },
          { name: "height", title: "Customer height", type: "string" },
          { name: "fitFeedback", title: "Fit feedback", type: "string", options: { list: [{ title: "Runs small", value: "runs-small" }, { title: "True to size", value: "true-to-size" }, { title: "Oversized", value: "oversized" }] } },
          { name: "orderId", title: "Order document (internal)", type: "string" },
        ],
        preview: { select: { title: "customerName", subtitle: "rating" } },
      }],
    },
    { name: "removed", title: "Removed from catalog", type: "boolean", initialValue: false },
  ],
};

export const orderSchema = {
  name: "order",
  title: "Order",
  type: "document",
  fields: [
    { name: "paymentProvider", title: "Payment provider", type: "string" },
    { name: "paymentReference", title: "Payment reference", type: "string" },
    { name: "orderNumber", title: "Customer order reference", type: "string" },
    { name: "paystackTransactionId", title: "Paystack transaction ID", type: "string" },
    { name: "reviewedProductSlugs", title: "Reviewed products (internal)", type: "array", of: [{ type: "string" }] },
    { name: "stripeSessionId", title: "Stripe Checkout Session", type: "string" },
    { name: "email", title: "Customer email", type: "string" },
    { name: "items", title: "Items", type: "array", of: [{ type: "object", fields: [{ name: "productId", type: "string" }, { name: "title", type: "string" }, { name: "size", type: "string" }, { name: "color", type: "string" }, { name: "quantity", type: "number" }, { name: "unitAmount", type: "number" }, { name: "dropName", type: "string" }] }] },
    { name: "amountTotal", title: "Total (minor units)", type: "number" },
    { name: "couponCode", title: "Discount code", type: "string" },
    { name: "discountAmount", title: "Discount (minor units)", type: "number" },
    { name: "currency", title: "Currency", type: "string" },
    { name: "stripePaymentIntentId", title: "Stripe payment intent", type: "string" },
    { name: "status", title: "Fulfillment status", type: "string", options: { list: ["paid", "packing", "shipped", "delivered", "cancelled", "inventory_issue"] } },
    { name: "shippingAddress", title: "Shipping address", type: "text" },
    { name: "trackingNumber", title: "Tracking number", type: "string" },
    { name: "gpsLocation", title: "Last courier GPS location", type: "object", fields: [{ name: "latitude", type: "number" }, { name: "longitude", type: "number" }, { name: "accuracy", type: "number" }, { name: "updatedAt", type: "datetime" }] },
    { name: "createdAt", title: "Created at", type: "datetime" },
    { name: "emailNotifiedAt", title: "Confirmation email sent at", type: "datetime" },
  ],
};

export const couponSchema = {
  name: "coupon",
  title: "Discount code",
  type: "document",
  fields: [
    { name: "code", title: "Code", type: "string", validation: (rule: { required: () => unknown }) => rule.required() },
    { name: "discountType", title: "Discount type", type: "string", options: { list: [{ title: "Percentage", value: "percentage" }, { title: "Fixed GHS amount", value: "fixed" }] }, validation: (rule: { required: () => unknown }) => rule.required() },
    { name: "discountValue", title: "Discount value", type: "number", validation: (rule: { required: () => { positive: () => unknown } }) => rule.required().positive() },
    { name: "active", title: "Active", type: "boolean", initialValue: true },
    { name: "usageCount", title: "Times used", type: "number", initialValue: 0 },
    { name: "maxUses", title: "Maximum uses", type: "number", validation: (rule: { integer: () => { min: (value: number) => unknown } }) => rule.integer().min(1) },
    { name: "startsAt", title: "Starts at", type: "datetime" },
    { name: "expiresAt", title: "Expires at", type: "datetime" },
  ],
  preview: { select: { title: "code", subtitle: "discountType" } },
};

export const restockAlertSchema = {
  name: "restockAlert",
  title: "Restock alert",
  type: "document",
  fields: [
    { name: "email", title: "Customer email", type: "string" },
    { name: "productSlug", title: "Product slug", type: "string" },
    { name: "productTitle", title: "Product title", type: "string" },
    { name: "size", title: "Size", type: "string" },
    { name: "active", title: "Awaiting restock", type: "boolean", initialValue: false },
    { name: "verified", title: "Email verified", type: "boolean", initialValue: false },
    { name: "confirmedAt", title: "Confirmed at", type: "datetime" },
    { name: "tokenHash", title: "Confirmation token hash", type: "string" },
    { name: "tokenExpiresAt", title: "Confirmation expires at", type: "datetime" },
    { name: "createdAt", title: "Subscribed at", type: "datetime" },
    { name: "notifiedAt", title: "Notified at", type: "datetime" },
  ],
  preview: { select: { title: "productTitle", subtitle: "size" } },
};

export default productSchema;